### ISSUE TITLE
Have interface in Atlas for reverting back to old versions of a file

### ISSUE THREAD

**Issue by sandersk** [MakerPress/atlas-public-feedback#73] opened 2012-08-30 23:31 UTC
The feedback in #72 has me think that it might be a nice enhancement to have a mechanism in the Atlas UI for reverting back to an older version of a file, something along the lines of the version history that WordPress and Google Docs have. You see a list of commits, and you can click a previous commit to revert back to that version (which does a "git revert").

**Comment by jhodgdon-drp** [comment] 2012-10-01 17:27
This seems to be a duplicate of issue #15 https://github.com/MakerPress/atlas-public-feedback/issues/15

**Closed as completed** 2014-03-26 21:57 UTC
Labels: enhancement
