### ISSUE TITLE
Latest Chimera build doesn't show images in "How to Contribute"

### ISSUE THREAD

**Issue by jdeisenberg** [MakerPress/atlas-public-feedback#233] opened 2013-03-20 16:51 UTC
This file: http://chimera.labs.oreilly.com/books/1234000000726/pr01.html doesn't show any images. The github repository (https://github.com/oreillymedia/etudes-for-erlang/tree/master/images) shows that the images are there, but I am not sure how to check for their presence at the Atlas repository.

**Comment by sandersk** [comment] 2013-03-21 16:56
Hi @jdeisenberg,

I've confirmed all the images are in the Git repository, so that's not the problem. It appears that there was an issue with our process that propagates images from Git to S3 for display on Chimera, but I'm having trouble reproducing the problem on other books.

@runemadsen, to further diagnose the problem, I added a new image to the images/ folder (tutorial_github_signup_testing.png, which is not referenced in the book). Then I rebuilt the HTML, and confirmed it got propagated to S3:

http://orm-chimera-prod.s3.amazonaws.com/1234000000726/images/tutorial_github_signup_testing.png

That seems to indicate to me that it was an one-time issue where a batch of images didn't get pushed to S3. And then the images didn't get uploaded to S3 on subsequent builds because our image-uploading process does a "git diff" and only pushes files that have changed since the last build.

My guess is that if we deleted all those pr01.html images from the Git repo, built the HTML, restored the images to the repo, and built again, they would propagate successfully to S3 this time, but I'm not sure. Rune, should we go ahead and do that, or are there further diagnostics you'd like to do first?

Thanks,
Sanders

**Comment by runemadsen** [comment] 2013-03-21 17:11
Thanks for looking into this @sandersk. 

That's quite weird. Maybe the html build broke before the images were uploaded or something? Let me take care of this. You're right that removing/adding the images would trigger an upload, but I can do it a bit faster, so I'll just do that.

Thanks for reporting this.

**Comment by runemadsen** [comment] 2013-03-21 17:15
This is fixed now. Please confirm and close the ticket. Thanks!

**Comment by nelliemckesson** [comment] 2013-03-21 17:15
If it helps with investigating: These images were originally loaded directly into a folder in S3 (orm-atlas-media), instead of being loaded into the /images folder for this specific book. Because of this, they weren't rendering in the PDF, so I copied them from that S3 folder into the book's /images dir, which fixed it. However, I also left them in the S3 folder, since I wasn't sure if they were also being used somewhere else. Maybe that's messing with the diff?

**Comment by runemadsen** [comment] 2013-03-21 17:22
Thanks @nelliemckesson. Maybe something weird happened there, yes. When you added the images to the repo, the HTML build should upload all images to S3, as it looks in the git log for changes to images since last build. Unless you specifically did some git rebasing, that shouldn't mess things up. Even then we have checks to fix that, so I'm not sure what happened. Oh well, if we see it again, I'll dive into the logs.

**Comment by jdeisenberg** [comment] 2013-03-21 20:35
Thank you; it looks great now.

**Closed as completed** 2013-03-21 20:35 UTC
