### ISSUE TITLE
Link gobbling up extra characters

### ISSUE THREAD

**Issue by jhodgdon-drp** [MakerPress/atlas-public-feedback#374] opened 2014-03-19 20:46 UTC
I have a URL in my Asciidoc source text, and when I run Atlas build to convert to a PDF, the link gobbles up some of the following text, and makes an invalid link. I tried putting the link on its own line, but it doesn't help.

The relevant lines in my Asciidoc source are:

```
from
https://drupal.org/project/examples
-- you could try out the Page and Block
```

And this is being rendered with

```
https://drupal.org/project/examples -- you
```

as both the link URL and link text. Which means the URL doesn't work.

It seems to be not recognizing the space or newline as the end of the link (it was a space previously and I recently changed it to a newline to see if that would help -- it behaved exactly the same).

**Comment by sandersk** [comment] 2014-03-22 16:18
Hi @jhdrupal,

I took a look, and the issue here is caused by the "order of operations" in AsciiDoc's regex parsing logic. In the markup above, the URL is followed by a newline and two hyphens, and then another space. AsciiDoc has a regex macro to convert two hyphens surrounded by whitespace into an em dash, but because that happens prior to parsing of the URL, it conflicts with the URL regex's logic in establishing the end-of-URL boundary.

The solution here is simply to use this alternative syntax for the URL:

```
https://drupal.org/project/examples[https://drupal.org/project/examples]
```

Which ensures everything parses properly. I've gone ahead and committed this change to your source files and confirmed the problem is fixed.

Please let us know if you encounter any further issues.

Thanks,
Sanders

**Closed as completed by sandersk** 2014-03-22 16:18 UTC
