### ISSUE TITLE
Issues copying/pasting from Word into Atlas when using Safari

### ISSUE THREAD

**Issue by sandersk** [MakerPress/atlas-public-feedback#199] opened 2013-01-29 22:36 UTC
Hi all,

@mikehatora was trying to get a Word doc into Atlas today, and he noticed that when he copied and pasted text from the Word file into Atlas, after he hit Save, the newlines disappeared.

I was able to reproduce the problem myself with several different Word documents using Word 2011 for Mac. Here is a screenshot of a chunk of text in the Atlas editor right after I pasted the text in from Word:

![atlas_before](https://f.cloud.github.com/assets/703865/108964/ec223e2e-6a63-11e2-9eff-fde12372ad94.png)

Then I click Save and switch to another document in the project. Then when I switch back to the original document, the following screenshot shows what the text looks like:

![atlas_after](https://f.cloud.github.com/assets/703865/108966/f36645d6-6a63-11e2-9805-6d221726d758.png)

Upon further testing, I discovered this problem happened when copying from Word 2011 to Atlas running in the Safari Web browser for Mac, but did not occur when copying and pasting from Word into Firefox for Mac. So the problem appears to be at least partially browser-dependent.

**Comment by mikehatora** [comment] 2013-01-30 00:33
It made no difference when I export to text with == and === already in 
the text file. As soon as I pasted it in, it looked fine. Save, exit 
file and then go back in and it is all gone.  This was from a text file 
massaged in TextMate too.  Bizarre.

Manual diddling is need now. I have to get this done.

**Comment by sandersk** [comment] 2013-06-18 14:41
Holly has experienced this same problem using Google Chrome. I think we should revisit this issue in Atlas v2 once we get the new editors in place.

**Comment by zaremba** [comment] 2014-05-09 20:15
I can't reproduce this in v2 beta in either HTML or Asciidoc, Safari and Firefox. So, I'm going to say that it's fixed in the newest version of Atlas. If it becomes a problem again, please let me know!

**Closed as completed by zaremba** 2014-05-09 20:15 UTC
Labels: bug
