### ISSUE TITLE
Changes tab always gives an error

### ISSUE THREAD

**Issue by paulbakker** [MakerPress/atlas-public-feedback#155] opened 2012-11-25 11:26 UTC
The changes view is not working at all, it always shows the not very informative "We're sorry, but something went wrong." error.

**Comment by runemadsen** [comment] 2012-11-25 21:44
Hi @paulbakker 

Thanks for the notice. This is a known issue, and is probably caused by you adding a binary file from the git command line. The changes tab is trying to parse all that binary data, and the request fails.

We're looking into this as soon as we can.

**Comment by sandersk** [comment] 2012-12-16 22:05
Hi @paulbakker

We recently released a software update that suppresses binaries for the changes tab and alleviates the "We're sorry, but something went wrong" issues. The changes tab is now working for your book, and you should not encounter this problem moving forward.

I'm going to go ahead and close this ticket, but could you please reopen and let us know if you see further problems with the Changes tab?

Thanks very much,
Sanders

**Closed as completed by sandersk** 2012-12-16 22:05 UTC
