### ISSUE TITLE
Atlas doesn't link to my Chimera account despite the same e-mail address for both

### ISSUE THREAD

**Issue by interested1** [MakerPress/atlas-public-feedback#280] opened 2013-07-05 21:38 UTC
I am working on a book in Atlas and was trying to use the sidebar commenting via Chimera, but I get the following error message:

"There was an error loading the comments from Chimera. For comments to load, you need to be logged into Chimera with the same email address as your Atlas user email. If the problem persists, please let us know"

My profile for Atlas as well as Chimera use the same e-mail address, so I am unsure what is going on and though it wise to let you know.

Thanks!
David

**Comment by runemadsen** [comment] 2013-07-05 23:36
Hi David

Are you logged into Chimera at the same time? Atlas will use your Chimera cookie to load the comments, so you need to be logged in on both sites. 

Let me know.
- Rune

**Comment by interested1** [comment] 2013-07-06 01:53
Rune,
  I opened a new tab first for Chimera and made sure I was logged in.  Then I opened a tab for Atlas.  Once again the same message appears in the sidebar.  Let me know what other steps I can do to help you figure this out.
David

**Comment by adamwitwer** [comment] 2013-07-08 12:43
Hi David. I wanted to take a look at this and try to reproduce with my account. Can you point me to the specific project? Thanks!

**Comment by interested1** [comment] 2013-07-08 18:49
1234000000814 is that what you need?

**Comment by adamwitwer** [comment] 2013-07-08 19:23
Thanks, @interested1. That helps. The problem was that you hadn't created an HTML version of the book yet. I went ahead and created it, and you can now see it here:  http://chimera.labs.oreilly.com/books/1234000000814/ch01.html. You'll need to be signed into the Chimera site to see that link, as it is private to you and your project collaborators.

I then made a test comment in the first chapter. Please see the attached screenshot, which shows how the comment bubbles over from Chimera to the writing environment. (You should be able to delete that comment.)

So it seems to be working as intended. Sorry for the confusion here. It's not always obvious how the two sites interact with one another.

![screen shot 2013-07-08 at 3 18 33 pm](https://f.cloud.github.com/assets/469435/763750/c187dd0e-e803-11e2-8001-9ff219345342.png)

I'll go ahead and close this issue, but please reopen if you see other problems related to this.

**Closed as completed by adamwitwer** 2013-07-08 19:23 UTC

**Comment by interested1** [comment] 2013-07-08 20:26
Adam,
   Nice work!  The comments are now working for me.  Just curious about the Chat and Commands section, though.  I understand the Chat idea, but I must have missed the docs on the Commands aspect, could you point me to the doc on this?

Thanks again for the resolution!
David

**Comment by adamwitwer** [comment] 2013-07-09 22:53
Hi David. I just realized I didn't answer your question about the commands. They aren't documented because it's a very experimental feature and we haven't gotten very far with it. You can give it a math equation in LaTeX and it'll output the equation as an image, e.g.: 

`atlas latexmath \begin{equation} {x = \frac{{ - b \pm \sqrt {b^2 - 4ac} }}{{2a}}} \end{equation}`

It might take a second or two to process. Or you can get a cute kitten like this: `atlas kitteh` 

Like I said, we haven't gotten very far with it. :smile:

**Comment by interested1** [comment] 2013-07-10 16:46
Thanks Adam, Brian told me about it yesterday and pointed me to Chapter 8 of the Atlas guide: http://chimera.labs.oreilly.com/books/1230000000065/ch08.html#_chat_and_commands

Hadn't gotten that far in the guide :-/ mostly just trying to bang out the book I am writing and learn Atlas on the side --writing locally with vim easier for me.

Thanks for all the help.
