### ISSUE TITLE
Build page doesn't hold list of files (book.asciidoc)

### ISSUE THREAD

**Issue by mrflip** [MakerPress/atlas-public-feedback#147] opened 2012-11-16 17:59 UTC
On 1230000000073 (Big Data for Chimps), the build page doesn't show the list of included files any more -- it used to be pre-populated. 

This started today (it worked a couple days ago).

**Comment by runemadsen** [comment] 2012-11-16 18:49
Thanks @mrflip. We're aware of this, and I'm working to fix it. I'll post an update when it's fixed.

**Comment by runemadsen** [comment] 2012-11-16 22:52
This should be fixed now. Let me know if you keep experiencing problems.

**Comment by sandersk** [comment] 2012-12-16 22:08
Hi @mrflip, I'm closing this ticket as we believe the problem is now resolved. Please reopen and let us know if you experience this problem again.

Thanks,
Sanders

**Closed as completed by sandersk** 2012-12-16 22:08 UTC
